[package]
name = "ithaca/project-name"
description = "No description provided."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Cmdr = "evaera/cmdr@1.12.0"
Observers = "sleitnick/observers@0.3.4"
Octotree = "sleitnick/octo-tree@0.3.1"
ProfileStore = "vyon/profilestore@1.0.3"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.0"
TableUtil = "sleitnick/table-util@1.2.1"
Timer = "sleitnick/timer@1.1.2"
Trove = "sleitnick/trove@1.5.0"